### ISSUE TITLE
detic_coco_base.pth link expired

### ISSUE THREAD

**Issue by ls1rius** [wusize/CLIM#4]
The checkpoint `detic_coco_base.pth` in [Google Drive](https://drive.google.com/file/d/1ZzR6aI-AnvSygUcJ7Ny8jOlY4v8Id7MO/view?usp=sharing) has expired. Can you please provide a new download link?
Thank you!!!

**Comment by wusize** [comment]
Hi, I am uploading files to [onedrive](https://entuedu-my.sharepoint.com/:f:/g/personal/size001_e_ntu_edu_sg/EthbRnDpAjpNoc6fewj2UBkBhEjQYCqU5mT4nminF8_uHA?e=ILHcXQ). It would be finished in two hours.

**Comment by ls1rius** [comment]
Thank you so much !

**Comment by kunpeng337** [comment]
> Hi, I am uploading files to [onedrive](https://entuedu-my.sharepoint.com/:f:/g/personal/size001_e_ntu_edu_sg/EthbRnDpAjpNoc6fewj2UBkBhEjQYCqU5mT4nminF8_uHA?e=ILHcXQ). It would be finished in two hours.您好，我正在上传文件到 [OneDrive](https://entuedu-my.sharepoint.com/:f:/g/personal/size001_e_ntu_edu_sg/EthbRnDpAjpNoc6fewj2UBkBhEjQYCqU5mT4nminF8_uHA?e=ILHcXQ) ，预计两个小时后完成。



Thank you for your outstanding work.
I found that there is a missing configuration file in the CLIM/scripts folder for training to generate 'openai_rn50x64_cc3m-clim. pt'.
If my findings are incorrect, please tell me how to train and generate the 'openai_rn50x64_cc3m_clim. pt' file.

My email is 120001098@qq.com
